name: Keep Render Server Awake 😼

on:
  schedule:
    - cron: "*/5 * * * *"   # Chạy mỗi 5 phút
  workflow_dispatch:        # Cho phép chạy thủ công
  push:
    branches:
      - main

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render server
        run: |
          curl -s -o /dev/null -w "%{http_code}" https://number-game-l446.onrender.com/ping
